CREATE TABLE IF NOT EXISTS pg_catalog.pg_class (
relname name NOT NULL,
relnamespace oid NOT NULL,
reltype oid NOT NULL,
reloftype oid NOT NULL,
relowner oid NOT NULL,
relam oid NOT NULL,
relfilenode oid NOT NULL,
reltablespace oid NOT NULL,
relpages integer NOT NULL,
reltuples real NOT NULL,
relallvisible integer NOT NULL,
reltoastrelid oid NOT NULL,
relhasindex boolean NOT NULL,
relisshared boolean NOT NULL,
relpersistence "char" NOT NULL,
relkind "char" NOT NULL,
relnatts smallint NOT NULL,
relchecks smallint NOT NULL,
relhasoids boolean NOT NULL,
relhaspkey boolean NOT NULL,
relhasrules boolean NOT NULL,
relhastriggers boolean NOT NULL,
relhassubclass boolean NOT NULL,
relrowsecurity boolean NOT NULL,
relforcerowsecurity boolean NOT NULL,
relispopulated boolean NOT NULL,
relreplident "char" NOT NULL,
relispartition boolean NOT NULL,
relfrozenxid xid NOT NULL,
relminmxid xid NOT NULL,
relacl ARRAY ,
reloptions ARRAY ,
relpartbound pg_node_tree 
);
GRANT TRIGGER, INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES on pg_catalog.pg_class to postgres;
GRANT SELECT on pg_catalog.pg_class to PUBLIC;
