CREATE TABLE IF NOT EXISTS information_schema.columns (
table_catalog character varying ,
table_schema character varying ,
table_name character varying ,
column_name character varying ,
ordinal_position integer ,
column_default character varying ,
is_nullable character varying ,
data_type character varying ,
character_maximum_length integer ,
character_octet_length integer ,
numeric_precision integer ,
numeric_precision_radix integer ,
numeric_scale integer ,
datetime_precision integer ,
interval_type character varying ,
interval_precision integer ,
character_set_catalog character varying ,
character_set_schema character varying ,
character_set_name character varying ,
collation_catalog character varying ,
collation_schema character varying ,
collation_name character varying ,
domain_catalog character varying ,
domain_schema character varying ,
domain_name character varying ,
udt_catalog character varying ,
udt_schema character varying ,
udt_name character varying ,
scope_catalog character varying ,
scope_schema character varying ,
scope_name character varying ,
maximum_cardinality integer ,
dtd_identifier character varying ,
is_self_referencing character varying ,
is_identity character varying ,
identity_generation character varying ,
identity_start character varying ,
identity_increment character varying ,
identity_maximum character varying ,
identity_minimum character varying ,
identity_cycle character varying ,
is_generated character varying ,
generation_expression character varying ,
is_updatable character varying 
);
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER on information_schema.columns to postgres;
GRANT SELECT on information_schema.columns to PUBLIC;
