CREATE TABLE IF NOT EXISTS information_schema.attributes (
udt_catalog character varying ,
udt_schema character varying ,
udt_name character varying ,
attribute_name character varying ,
ordinal_position integer ,
attribute_default character varying ,
is_nullable character varying ,
data_type character varying ,
character_maximum_length integer ,
character_octet_length integer ,
character_set_catalog character varying ,
character_set_schema character varying ,
character_set_name character varying ,
collation_catalog character varying ,
collation_schema character varying ,
collation_name character varying ,
numeric_precision integer ,
numeric_precision_radix integer ,
numeric_scale integer ,
datetime_precision integer ,
interval_type character varying ,
interval_precision integer ,
attribute_udt_catalog character varying ,
attribute_udt_schema character varying ,
attribute_udt_name character varying ,
scope_catalog character varying ,
scope_schema character varying ,
scope_name character varying ,
maximum_cardinality integer ,
dtd_identifier character varying ,
is_derived_reference_attribute character varying 
);
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER on information_schema.attributes to postgres;
GRANT SELECT on information_schema.attributes to PUBLIC;
