CREATE TABLE IF NOT EXISTS pg_catalog.pg_type (
typname name NOT NULL,
typnamespace oid NOT NULL,
typowner oid NOT NULL,
typlen smallint NOT NULL,
typbyval boolean NOT NULL,
typtype "char" NOT NULL,
typcategory "char" NOT NULL,
typispreferred boolean NOT NULL,
typisdefined boolean NOT NULL,
typdelim "char" NOT NULL,
typrelid oid NOT NULL,
typelem oid NOT NULL,
typarray oid NOT NULL,
typinput regproc NOT NULL,
typoutput regproc NOT NULL,
typreceive regproc NOT NULL,
typsend regproc NOT NULL,
typmodin regproc NOT NULL,
typmodout regproc NOT NULL,
typanalyze regproc NOT NULL,
typalign "char" NOT NULL,
typstorage "char" NOT NULL,
typnotnull boolean NOT NULL,
typbasetype oid NOT NULL,
typtypmod integer NOT NULL,
typndims integer NOT NULL,
typcollation oid NOT NULL,
typdefaultbin pg_node_tree ,
typdefault text ,
typacl ARRAY 
);
GRANT TRIGGER, INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES on pg_catalog.pg_type to postgres;
GRANT SELECT on pg_catalog.pg_type to PUBLIC;
