CREATE TABLE IF NOT EXISTS pg_catalog.pg_statistic (
starelid oid NOT NULL,
staattnum smallint NOT NULL,
stainherit boolean NOT NULL,
stanullfrac real NOT NULL,
stawidth integer NOT NULL,
stadistinct real NOT NULL,
stakind1 smallint NOT NULL,
stakind2 smallint NOT NULL,
stakind3 smallint NOT NULL,
stakind4 smallint NOT NULL,
stakind5 smallint NOT NULL,
staop1 oid NOT NULL,
staop2 oid NOT NULL,
staop3 oid NOT NULL,
staop4 oid NOT NULL,
staop5 oid NOT NULL,
stanumbers1 ARRAY ,
stanumbers2 ARRAY ,
stanumbers3 ARRAY ,
stanumbers4 ARRAY ,
stanumbers5 ARRAY ,
stavalues1 anyarray ,
stavalues2 anyarray ,
stavalues3 anyarray ,
stavalues4 anyarray ,
stavalues5 anyarray 
);
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER on pg_catalog.pg_statistic to postgres;
